//! Use cases. Depend only on the domain and on the ports declared in `ports`.
pub mod account_settings;
pub mod accounts;
mod action_runner;
pub mod agent_bots;
mod attachments;
pub mod auto_replies;
pub mod automations;
pub mod avatars;
pub mod bulk;
pub mod catalog;
mod contact_channels;
mod contact_csv;
mod contacts;
mod conversation_actions;
mod conversation_tools;
pub mod core;
pub mod crypto;
pub mod custom_data;
pub mod event_bus;
pub mod events;
pub mod helpdesk;
mod ingestion;
pub mod macros;
pub mod menu;
mod message_actions;
pub mod notifications;
pub mod oauth;
mod oauth_tokens;
pub mod ports;
mod presence;
pub mod replies;
pub mod reports;
pub mod reports_v2;
pub mod roles;
pub mod search;
pub mod security;
pub mod sessions;
mod signature;
mod sla;
mod teams;
pub mod webhooks;
pub mod whatsapp_sink;
