import { TriangleAlert } from 'lucide-react';
import { Button } from '../../ui/Button';
import { Modal } from '../../ui/Overlay';
import { SecretField } from '../../ui/SecretField';

/** The bot access token, shown once, with a warning to copy it now. */
export function TokenNotice({ token, onDone }: { token: string; onDone: () => void }) {
  return (
    <div className="flex flex-col gap-4">
      <p className="flex gap-2 rounded-lg bg-n-amber-9/10 px-3 py-2 text-sm text-n-amber-11">
        <TriangleAlert size={16} className="mt-0.5 shrink-0" />
        Copie o token agora: por segurança ele não será exibido novamente. O robô o envia no cabeçalho
        api_access_token.
      </p>
      <SecretField label="Token de acesso" copyLabel="Copiar token" secret={token} />
      <div className="flex justify-end">
        <Button label="Concluir" onClick={onDone} />
      </div>
    </div>
  );
}

/** Modal with the token generated by "Gerar novo token". */
export function TokenModal({ name, token, onClose }: { name: string; token: string; onClose: () => void }) {
  return (
    <Modal title={`Novo token de ${name}`} onClose={onClose}>
      <TokenNotice token={token} onDone={onClose} />
    </Modal>
  );
}
